//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unbrickable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackUp
    {
        public int id { get; set; }
        public string file_location { get; set; }
        public int num_posts { get; set; }
        public System.DateTime date_uploaded { get; set; }
    }
}
