
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Unbrickable.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Post
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Post()
    {

        this.LinkedItems = new HashSet<LinkedItem>();

    }


    public int id { get; set; }

    public int account_id { get; set; }

    public System.DateTime date_posted { get; set; }

    public Nullable<System.DateTime> date_edited { get; set; }

    public Nullable<int> editor_id { get; set; }

    public string entry { get; set; }



    public virtual Account Account { get; set; }

    public virtual Account Editor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LinkedItem> LinkedItems { get; set; }

}

}
