
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Unbrickable.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Transaction
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Transaction()
    {

        this.TransactionItems = new HashSet<TransactionItem>();

    }


    public int id { get; set; }

    public int account_id { get; set; }

    public int transaction_status_id { get; set; }

    public string paypal_transaction_id { get; set; }

    public System.DateTime date_of_transaction { get; set; }



    public virtual Account Account { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TransactionItem> TransactionItems { get; set; }

    public virtual TransactionStatus TransactionStatus { get; set; }

}

}
